# Docker Compose for development/testing
version: '3.8'

services:
  minecraft-server:
    build: .
    ports:
      - "25565:25565"
    environment:
      - EULA=true
      - JAVA_OPTS=-Xmx4G -Xms4G -Dlog4j2.formatMsgNoLookups=true
    volumes:
      - minecraft_world:/minecraft/world
      - minecraft_logs:/minecraft/logs
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  minecraft_world:
  minecraft_logs:
